name: CI

on:
  pull_request:
  push:
    branches: [ master ]   # change to 'main' if needed

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build & test all modules
        run: |
          mvn -V -B -ntp verify
