name: Publish

on:
  push:
    branches: [ master ]       # SNAPSHOT deploys
    tags: [ 'v*' ]             # release deploys

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write      # for GitHub Packages
      id-token: write      # for GitHub token
    env:
      # Common Maven flags
      MAVEN_ARGS: -V -B -ntp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      

      - name: Set up JDK + Maven auth
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github                # must match <distributionManagement>/<id> in POM
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Show project version
        id: mvn_version
        run: |
          ver=$(grep -oP '<version>\K[^<]+' pom.xml | head -n 1)
          echo "version=$ver" >> $GITHUB_OUTPUT

      - name: Debug POM and Maven settings
        run: |
          echo "=== POM Distribution Management ==="
          grep -A 10 "distributionManagement" pom.xml
          echo "=== Maven Settings ==="
          mvn help:effective-settings -DshowPasswords=false | grep -A 5 -B 5 "github"
          echo "=== Testing GitHub Packages Access ==="
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/user/packages/maven/org.saltations.endeavour



      # Optional sanity: fail if trying to deploy a SNAPSHOT on a tag or a release on master
      - name: Guard rails
        run: |
          ver="${{ steps.mvn_version.outputs.version }}"
          ref="${GITHUB_REF}"
          if [[ "$ref" == refs/tags/* ]]; then
            if [[ "$ver" == *-SNAPSHOT ]]; then
              echo "Tag build but project version is SNAPSHOT ($ver). Refuse to deploy."
              exit 1
            fi
          else
            if [[ "$ver" != *-SNAPSHOT ]]; then
              echo "Master build but project version is RELEASE ($ver). Refuse to deploy."
              exit 1
            fi
          fi

      # Deploy snapshots on pushes to master
      - name: Deploy SNAPSHOTs (master)
        if: startsWith(github.ref, 'refs/heads/')
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn $MAVEN_ARGS -DskipTests deploy 

      # Deploy releases on version tags (e.g., v1.2.3)
      - name: Deploy RELEASE (tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # For Sonatype central: include 'clean deploy -P release' or your signing profile
          mvn $MAVEN_ARGS -DskipTests deploy

    
