name: Publish

on:
  push:
    branches: [ master ]       # SNAPSHOT deploys
    tags: [ 'v*' ]             # release deploys

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write      # for GitHub Packages (if you use it)
    env:
      # Common Maven flags
      MAVEN_ARGS: -V -B -ntp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      

      - name: Set up JDK + Maven auth
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github                # must match <distributionManagement>/<id> in POM
          server-username: GITHUB_ACTOR
          server-password: ${{ github.token }}

      - name: Show project version
        id: mvn_version
        run: |
          ver=$(grep -oP '<version>\K[^<]+' pom.xml | head -n 1)
          echo "version=$ver" >> $GITHUB_OUTPUT



      # Optional sanity: fail if trying to deploy a SNAPSHOT on a tag or a release on master
      - name: Guard rails
        run: |
          ver="${{ steps.mvn_version.outputs.version }}"
          ref="${GITHUB_REF}"
          if [[ "$ref" == refs/tags/* ]]; then
            if [[ "$ver" == *-SNAPSHOT ]]; then
              echo "Tag build but project version is SNAPSHOT ($ver). Refuse to deploy."
              exit 1
            fi
          else
            if [[ "$ver" != *-SNAPSHOT ]]; then
              echo "Master build but project version is RELEASE ($ver). Refuse to deploy."
              exit 1
            fi
          fi

      # Deploy snapshots on pushes to master
      - name: Deploy SNAPSHOTs (master)
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          mvn $MAVEN_ARGS -DskipTests deploy

      # Deploy releases on version tags (e.g., v1.2.3)
      - name: Deploy RELEASE (tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # For Sonatype central: include 'clean deploy -P release' or your signing profile
          mvn $MAVEN_ARGS -DskipTests deploy

    
